function newConfirm(idxCand, pc)
% 将候选区轨迹添加到确立区
% 输入: 
% 1. idxCand: 待转入确立区的候选区轨迹索引
% 2. pc: 待转入确立区的关联点云簇的点云
% 作者: 刘涵凯
% 更新: 2023-3-9

%% 参数对象及全局变量
p = trackParamShare.param;
global iFrm trackCand trackConfirm trajectory

%% 多次平滑
for iSmooth = 1 : p.nSmthNewConfirm
    trackCand(idxCand).trajectory = smoothdataV3(trackCand(idxCand).trajectory, 1, p.smthMeth, p.smthWin);
end

%% 新建确立区轨迹
p.nPpl = p.nPpl + 1;
nOldTraj = structLength(trackConfirm, 'centroid');
trackConfirm(nOldTraj + 1) = struct('centroid', trackCand(idxCand).centroid, ...
    'kalmanFilter', createNewKF(trackCand(idxCand).centroid, 'motionType', p.motionType), ...
    'iPeople', p.nPpl, ...
    'name', "N", ...
    'pc', pc, ...
    'status', "active", ...
    'statusAge', 1, ...
    'trajectory', trackCand(idxCand).trajectory(1 : end - 1, :), ...
    'frame', trackCand(idxCand).frame(1 : end - 1)); % 注意end - 1, 因为此值会在renewTrajectory中更新

%% 在轨迹结构体中新建确立轨迹
% 注意新建的时刻为上一帧
nOldTraj = structLength(trajectory(iFrm - 1).track, 'iPeople');
trajectory(iFrm - 1).track(nOldTraj + 1) = struct('iPeople', trackConfirm(end).iPeople, ...
    'name', trackConfirm(end).name, ...
    'trajectory', trackConfirm(end).trajectory, ...
    'frame', trackConfirm(end).frame, ...
    'status', trackConfirm(end).status, ...
    'pcLast', pc, ...
    'kalmanFilter', trackConfirm(end).kalmanFilter, ...
    'statusAge', 1);
