function newConfirm_modified(idxCand, pc)
% 将候选区轨迹添加到确立区

p = trackParamShare.param;
global iFrm trackCand trackConfirm trajectory

traj = trackCand(idxCand).trajectory;
nTraj = size(traj, 1);
if nTraj >= 2
    winUse = min(p.smthWin, nTraj);
    for iSmooth = 1 : p.nSmthNewConfirm
        traj = smoothdataV3(traj, 1, p.smthMeth, winUse);
    end
    trackCand(idxCand).trajectory = traj;
end

p.nPpl = p.nPpl + 1;
nOldTraj = structLength(trackConfirm, 'centroid');
trackConfirm(nOldTraj + 1) = struct('centroid', trackCand(idxCand).centroid, ...
    'kalmanFilter', createNewKF(trackCand(idxCand).centroid, 'motionType', p.motionType), ...
    'iPeople', p.nPpl, ...
    'name', "N", ...
    'pc', pc, ...
    'status', "active", ...
    'statusAge', 1, ...
    'trajectory', trackCand(idxCand).trajectory(1 : max(end - 1, 1), :), ...
    'frame', trackCand(idxCand).frame(1 : max(end - 1, 1)));

nOldTraj = structLength(trajectory(iFrm - 1).track, 'iPeople');
trajectory(iFrm - 1).track(nOldTraj + 1) = struct('iPeople', trackConfirm(end).iPeople, ...
    'name', trackConfirm(end).name, ...
    'trajectory', trackConfirm(end).trajectory, ...
    'frame', trackConfirm(end).frame, ...
    'status', trackConfirm(end).status, ...
    'pcLast', pc, ...
    'kalmanFilter', trackConfirm(end).kalmanFilter, ...
    'statusAge', 1);
end
